services:
    - type: web
      runtime: 'node'
      repo: https://github.com/cinepro-org/core
      name: cinepro-core
      plan: free
      autoDeploy: true
      numInstances: 1
      buildCommand: npm install && npm run build
      startCommand: npm run start

      envVars:
          - key: NODE_ENV
            value: 'production'
          - key: HOST
            value: '0.0.0.0'
          - key: PUBLIC_URL
            value: 'https://cineverse-core.onrender.com'
          - key: CACHE_TYPE
            value: 'memory'
          - key: TMDB_API_KEY
            value: ''
          - key: CORS_ORIGIN
            value: '*'
          
